In [3]:
import pandas as pd  # Pandas for data manipulation and handling DataFrame objects
from sklearn.model_selection import train_test_split  # Scikit-learn's function to split data into train and test sets
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification  # HuggingFace Transformers for tokenization and model
from transformers import Trainer, TrainingArguments  # HuggingFace Trainer API for model training and fine-tuning
from datasets import Dataset  # HuggingFace datasets library to handle dataset objects and easy integration with models
import torch  # PyTorch for tensor operations and model handling
from sklearn.metrics import classification_report, confusion_matrix  # Scikit-learn for generating classification metrics

In [4]:
df = pd.read_csv("train.csv")
df

text              intent
0       listen to westbam alumb allergic on google music           PlayMusic
1             add step to me to the 50 clásicos playlist       AddToPlaylist
2      i give this current textbook a rating value of...            RateBook
3                   play the song little robin redbreast           PlayMusic
4      please add iris dement to my playlist this is ...       AddToPlaylist
...                                                  ...                 ...
13079      i want to eat choucroute at a brasserie for 8      BookRestaurant
13080                            play funky heavy bluesy           PlayMusic
13081           rate the current album 2 points out of 6            RateBook
13082             go to the photograph the inflated tear  SearchCreativeWork
13083                     rate richard carvel 4 out of 6            RateBook

[13084 rows x 2 columns]

In [5]:
df['intent'].value_counts()

intent
PlayMusic               1914
GetWeather              1896
BookRestaurant          1881
RateBook                1876
SearchScreeningEvent    1852
SearchCreativeWork      1847
AddToPlaylist           1818
Name: count, dtype: int64

In [6]:
df.shape

(13084, 2)

In [7]:
df = df.sample(n=3000)

In [8]:
df.isnull().sum()

text      0
intent    0
dtype: int64

In [9]:
df['intent'] = df['intent'].apply(lambda x: x.lower())

In [10]:
import nltk
from nltk.corpus import stopwords

# Download NLTK stopwords (only need to do this once)
nltk.download('stopwords')
# Load the list of stopwords
stop_words = set(stopwords.words('english'))


# Preprocessing function: convert text to lowercase and remove stopwords
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove stopwords: split the text, filter out stopwords, and join back
    text = ' '.join([word for word in text.split() if word not in stop_words])

    return text

# Example usage
text_input = 'Stop to play music'

# Preprocess the text
processed_text = preprocess_text(text_input)
print(f"Processed Text: {processed_text}")

Processed Text: stop play music


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [11]:
df['text'] = df['text'].apply(preprocess_text)

In [15]:
# Check the unique labels in the 'Intent_Label' column
unique_labels = df['intent'].unique()
unique_labels


array(['playmusic', 'searchscreeningevent', 'ratebook', 'bookrestaurant',
       'getweather', 'addtoplaylist', 'searchcreativework'], dtype=object)

In [17]:
# Create a mapping from labels to numbers (numeric encoding)
label_to_id = {label: i for i, label in enumerate(unique_labels)}

print(label_to_id)

{'playmusic': 0, 'searchscreeningevent': 1, 'ratebook': 2, 'bookrestaurant': 3, 'getweather': 4, 'addtoplaylist': 5, 'searchcreativework': 6}


In [18]:
# Map the 'Intent_Label' to numeric labels in the 'Label' column
df['Label'] = df['intent'].map(label_to_id)

# Check the updated DataFrame
df.head()

text  \
11178             play twenties track aj carothers zvooq   
8647                                find movie schedules   
9171                      giving book series four points   
4916                         play nineties music pandora   
2736   eight seconds like reservations food court ser...   

                     intent  Label  
11178             playmusic      0  
8647   searchscreeningevent      1  
9171               ratebook      2  
4916              playmusic      0  
2736         bookrestaurant      3

In [19]:
# Load the DistilBERT tokenizer
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")  # Load pre-trained DistilBERT tokenizer


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

In [20]:
# Calculate the maximum tokenized length from the dataset
max_length = max([len(tokenizer.encode(text)) for text in df['text']])  # Tokenize and count the length of each tokenized text
print("Max Length:", max_length)



Max Length: 28


In [21]:
# Tokenization function with labels
def tokenize_function(examples):  # Define a function to tokenize inputs and add labels
    tokenized_input = tokenizer(examples['text'], padding='max_length', truncation=True, max_length=max_length)  # Use the max_length calculated above
    tokenized_input['labels'] = examples['Label']  # Add labels to the tokenized data for supervised training
    return tokenized_input  # Return tokenized data with labels


dataset = Dataset.from_pandas(df[['text', 'Label']])  # Convert the DataFrame into a HuggingFace Dataset


In [23]:
# Apply tokenization
dataset = dataset.map(tokenize_function, batched=True)  # Apply the tokenization function to the dataset

# Check tokenized data
#dataset[0]  # Display the tokenized version of the first example in the dataset to verify the transformation


Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

In [24]:
# Initialize DistilBERT model for sequence classification
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=len(unique_labels))


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [26]:
from transformers import TrainingArguments, Trainer  # Import necessary classes from Hugging Face

# Training arguments
training_args = TrainingArguments(  # Define the training configurations
    output_dir="./results",  # Directory to save results (model checkpoints, logs, etc.)
    eval_strategy="epoch",  # Evaluate the model at the end of each epoch
    learning_rate=2e-5,  # Set learning rate for the optimizer
    per_device_train_batch_size=16,  # Batch size for training (number of examples per device)
    per_device_eval_batch_size=64,  # Batch size for evaluation
    num_train_epochs=3,  # Number of epochs to train the model
    weight_decay=0.01,  # L2 regularization to avoid overfitting
    logging_dir="./logs",  # Directory to store training logs
    logging_steps=10,  # Log training information every 10 steps
)

# Trainer setup
trainer = Trainer(  # Initialize the Trainer with the model and training configurations
    model=model,  # Model to be trained
    args=training_args,  # Training arguments
    train_dataset=dataset,  # Training dataset
    eval_dataset=dataset,  # Validation dataset (in practice, this should be a separate dataset)
)

# Train the model
trainer.train()  # Start training the model based on the provided training arguments

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.


<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········


wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: studymaterialvk2023 (studymaterialvk2023-chase) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


TrainOutput(global_step=564, training_loss=0.2961644168863905, metrics={'train_runtime': 140.2456, 'train_samples_per_second': 64.173, 'train_steps_per_second': 4.022, 'total_flos': 65204611416000.0, 'train_loss': 0.2961644168863905, 'epoch': 3.0})

In [27]:
from sklearn.metrics import classification_report, confusion_matrix

# Evaluate the model on the test dataset
predictions, true_labels, _ = trainer.predict(dataset)

# Convert predictions to label indices
predicted_labels = predictions.argmax(axis=1)

# Generate classification report and confusion matrix
print("Classification Report:")
print(classification_report(true_labels, predicted_labels))

print("Confusion Matrix:")
print(confusion_matrix(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       430
           1       1.00      0.98      0.99       462
           2       1.00      1.00      1.00       410
           3       1.00      1.00      1.00       416
           4       1.00      1.00      1.00       445
           5       1.00      1.00      1.00       402
           6       0.98      0.97      0.97       435

    accuracy                           0.99      3000
   macro avg       0.99      0.99      0.99      3000
weighted avg       0.99      0.99      0.99      3000

Confusion Matrix:
[[427   0   0   0   0   1   2]
 [  0 455   0   0   0   0   7]
 [  0   0 410   0   0   0   0]
 [  0   0   0 416   0   0   0]
 [  0   0   0   1 444   0   0]
 [  1   0   1   0   0 400   0]
 [ 12   2   0   0   0   0 421]]


In [28]:
# Save the model and tokenizer
model.save_pretrained('./saved_fine_tuned_model')
tokenizer.save_pretrained('./saved_fine_tuned_model')

('./saved_fine_tuned_model/tokenizer_config.json',
 './saved_fine_tuned_model/special_tokens_map.json',
 './saved_fine_tuned_model/vocab.txt',
 './saved_fine_tuned_model/added_tokens.json')

In [29]:
# Load the fine-tuned model and tokenizer for inference
model = DistilBertForSequenceClassification.from_pretrained('./saved_fine_tuned_model')
tokenizer = DistilBertTokenizer.from_pretrained('./saved_fine_tuned_model')

In [30]:
# Now create the reverse mapping for inference
id_to_label = {i: label for label, i in label_to_id.items()}  # Reverse the mapping
id_to_label

{0: 'playmusic',
 1: 'searchscreeningevent',
 2: 'ratebook',
 3: 'bookrestaurant',
 4: 'getweather',
 5: 'addtoplaylist',
 6: 'searchcreativework'}

In [31]:
# Function to make a prediction
def predict(text, model, tokenizer, max_length=21):
    # Preprocess the input text
    text = preprocess_text(text)
    # Tokenize the input text
    inputs = tokenizer(text, padding='max_length', truncation=True, max_length=max_length, return_tensors="pt")

    # Make prediction
    with torch.no_grad():  # Disable gradient calculation for inference
        outputs = model(**inputs)  # Get model output
        logits = outputs.logits  # Get logits from the output

    # Get the predicted label (highest logit)
    predicted_class_id = torch.argmax(logits, dim=-1).item()  # Get the index of the max logit
    return predicted_class_id

In [33]:
# Define the intent labels
id_to_label = {
    0: 'getweather',
    1: 'searchcreativework',
    2: 'searchscreeningevent',
    3: 'addtoplaylist',
    4: 'bookrestaurant',
    5: 'ratebook',
    6: 'playmusic'
}

# Example messages for testing
test_messages = [
    "What's the weather like today?",
    "Find me a creative project about AI.",
    "Are there any events screening this weekend?",
    "Add this song to my playlist.",
    "I'd like to book a table for two.",
    "Rate the book I just finished reading.",
    "Play some relaxing music.",
    "Can you find a documentary on climate change?",
    "What time does the movie start tonight?",
    "Add the new album to my library."
]

# Test the model with the example messages
for message in test_messages:
    predicted_label = predict(message, model, tokenizer)
    predicted_intent = id_to_label.get(predicted_label, "Unknown Intent")
    print(f"Message: {message}")
    print(f"Predicted Label: {predicted_label}, Predicted Intent: {predicted_intent}\n")


Message: What's the weather like today?
Predicted Label: 4, Predicted Intent: bookrestaurant

Message: Find me a creative project about AI.
Predicted Label: 6, Predicted Intent: playmusic

Message: Are there any events screening this weekend?
Predicted Label: 1, Predicted Intent: searchcreativework

Message: Add this song to my playlist.
Predicted Label: 5, Predicted Intent: ratebook

Message: I'd like to book a table for two.
Predicted Label: 3, Predicted Intent: addtoplaylist

Message: Rate the book I just finished reading.
Predicted Label: 2, Predicted Intent: searchscreeningevent

Message: Play some relaxing music.
Predicted Label: 0, Predicted Intent: getweather

Message: Can you find a documentary on climate change?
Predicted Label: 6, Predicted Intent: playmusic

Message: What time does the movie start tonight?
Predicted Label: 1, Predicted Intent: searchcreativework

Message: Add the new album to my library.
Predicted Label: 5, Predicted Intent: ratebook



In [34]:
import shutil

# Path to save the model
model_dir = "/content/saved_fine_tuned_model"
model.save_pretrained(model_dir)  # Save the model
tokenizer.save_pretrained(model_dir)  # Save the tokenizer

# Zip the model folder
shutil.make_archive("distilbert_model", 'zip', model_dir)

# Download the zipped model
from google.colab import files
files.download("distilbert_model.zip")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>